apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_DB: projecto
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Ec94
  DB_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  DB_HOST: db
  DB_NAME: projecto
  DB_USER: postgres
  DB_PASSWORD: Ec94
  DB_PORT: "5432"
