apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000        # Puerto en el que estará expuesto externamente
      targetPort: 8000
      nodePort: 30080
  type: NodePort     # Cambia el tipo de servicio a NodePort
