apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ervincaravaliibarra/galeria-20:latest
          command: ["sh", "-c", "sleep 10 && python manage.py runserver 0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: DB_PASSWORD
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: DB_PORT
          resources: # Aquí se define la sección de recursos
            requests: # Recursos mínimos requeridos
              memory: "64Mi" # 64 megabytes de memoria RAM
              cpu: "250m"    # 250 milicpus (0.25 CPUs)
            limits:   # Límites máximos permitidos
              memory: "128Mi" # 128 megabytes de memoria RAM
              cpu: "500m"     # 500 milicpus (0.5 CPUs)
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
