name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Kubernetes
      env:
        KUBE_CONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64 }}
      run: |
        echo "$KUBE_CONFIG_BASE64" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f .github/manifests/db-deployment.yaml -n backend
        kubectl apply -f .github/manifests/web-deployment.yaml -n backend
        kubectl apply -f .github/manifests/configmap.yaml -n backend
        kubectl apply -f .github/manifests/web-service.yaml -n backend
