name: Deploy to Kubernetes

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure kubectl
        uses: ghostzero/kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.11.0
        with:
          minikube version: 'v1.33.0'
          kubernetes version: 'v1.30.0'

      - name: Interact with the cluster
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl get nodes
          kubectl create namespace backend || true
          kubectl apply -f .github/manifests/db-deployment.yaml -n backend
          kubectl apply -f .github/manifests/web-deployment.yaml -n backend
          kubectl apply -f .github/manifests/configmap.yaml -n backend
          kubectl apply -f .github/manifests/web-service.yaml -n backend
          kubectl get all -n backend
          
      - name: Port-forward web-service
        run: kubectl port-forward service/web-service 30130:3120 -n backend
