name: CD

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Read kubeconfig_base64.txt
        id: read_kubeconfig
        run: |
          KUBE_CONFIG_BASE64=$(cat kubeconfig_base64.txt)
          echo "::set-output name=kubeconfig_base64::$KUBE_CONFIG_BASE64"

      - name: Authenticate to cluster
        env:
          KUBE_CONFIG_DATA: ${{ steps.read_kubeconfig.outputs.kubeconfig_base64 }}
        run: |
          mkdir -p $HOME/.kube
          echo $KUBE_CONFIG_DATA | base64 --decode > $HOME/.kube/config

      - name: Apply manifests
        run: |
          kubectl apply -f .github/manifests/db-deployment.yaml -n backend
          kubectl apply -f .github/manifests/web-deployment.yaml -n backend
          kubectl apply -f .github/manifests/configmap.yaml -n backend
          kubectl apply -f .github/manifests/web-service.yaml -n backend
