name: CD

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-cluster:
    name: Deploy to cluster
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy to cluster
        run: kubectl -n prueba set image --record deployment/web-service web-service=pablokbs/web-service:${{ github.sha }}

      - name: Verify deployment
        run: kubectl -n prueba rollout status deployment/web-service
