name: CD

on:
  pull_request:
    branches:
      - main

jobs:
  download_docker_images:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker images
        run: |
          docker pull ervincaravaliibarra/galeria-20:latest || exit 1
          docker pull ervincaravaliibarra/bdgaleria-20:latest || exit 1

  deploy_to_cluster:
    name: Deploy to cluster
    runs-on: windows-latest
    needs: download_docker_images
    steps:
      - name: Configure kubectl
        uses: steebchen/kubectl@v2.0.0
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Set Kubernetes context
        run: |
          kubectl config set-cluster minikube \
            --server=https://172.22.27.150:8443 \
            --certificate-authority="C:\Users\Ervin Caravali\.minikube\ca.crt" \
            --embed-certs=true
          kubectl config use-context minikube
          
      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace backend || true
          kubectl apply -f .github/manifests/configmap.yaml -n backend
          kubectl apply -f .github/manifests/db-deployment.yaml -n backend
          kubectl apply -f .github/manifests/web-deployment.yaml -n backend
          kubectl apply -f .github/manifests/web-service.yaml -n backend
          kubectl get all -n backend
