name: Automatización de Kubernetes

on:
  push:
    branches:
      - feature/ervin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      
    - name: Configurar Kubernetes
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.KUBE_CONFIG_DATA }}
        cluster-name: my-cluster-name
        resource-group: my-resource-group-name

    - name: Aplicar cambios en Kubernetes
      run: |
        kubectl apply -f web-service.yaml -n backend
        kubectl get all -n backend
        kubectl get svc istio-ingressgateway -n istio-system
        kubectl get namespaces
        kubectl get all -n backend
        kubectl get services -n backend
        kubectl port-forward service/web-service 30130:3120 -n backend
