name: Deploy on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.11.0

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Configure kubectl
        uses: steebchen/kubectl@v2.0.0
        with:
          args: config set-context minikube

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kubectl in Minikube
        run: minikube kubectl -- get nodes

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker images
        run: docker pull ervincaravaliibarra/galeria-20
        run: docker pull ervincaravaliibarra/bdgaleria-20


      - name: Deploy to Kubernetes
        run: kubectl apply -f .github/manifests -n backend

      - name: Get deployed resources
        run: kubectl get all -n backend
