name: Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create/Modify deployment
        uses: gane5hvarma/kubectl-actions@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f .github/manifests/db-deployment.yaml -f .github/manifests/web-deployment.yaml -f .github/manifests/configmap.yaml -f .github/manifests/web-service.yaml -n backend