name: Deploy to Kubernetes

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure kubectl
        uses: ghostzero/kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace backend
          kubectl label namespace backend istio-injection=enabled
          kubectl apply -f db-deployment.yaml -n backend
          kubectl apply -f web-deployment.yaml -n backend
          kubectl apply -f configmap.yaml -n backend
          kubectl apply -f web-service.yaml -n backend
          kubectl get all -n backend
