name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-cluster:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Set up kubectl
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Apply DB Deployment
        run: kubectl apply -f db-deployment.yaml

      - name: Apply Web Deployment
        run: kubectl apply -f web-deployment.yaml

      - name: Apply Web Service
        run: kubectl apply -f web-service.yaml

      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.28"
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: -n prueba rollout status deployment/web-service
