name: Deploy to Kubernetes

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Kubernetes
      run: |
        mkdir -p $HOME/.kube
        cp kubeconfig.yaml $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f .github/manifests/db-deployment.yaml -n backend
        kubectl apply -f .github/manifests/web-deployment.yaml -n backend
        kubectl apply -f .github/manifests/configmap.yaml -n backend
        kubectl apply -f .github/manifests/web-service.yaml -n backend
