name: Desplegar en Kubernetes

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar Kubernetes
      run: |
        # Leer el contenido codificado en base64 del archivo
        KUBE_CONFIG_BASE64=$(cat kubeconfig_base64.txt)
        # Crear el directorio .kube
        mkdir -p $HOME/.kube
        # Decodificar la cadena base64 y escribirla en el archivo de configuración de Kubernetes
        echo "$KUBE_CONFIG_BASE64" | base64 -d > $HOME/.kube/config
        # Establecer los permisos apropiados en el archivo de configuración
        chmod 600 $HOME/.kube/config

    - name: Desplegar en Kubernetes
      run: |
        kubectl apply -f .github/manifests/db-deployment.yaml 
        kubectl apply -f .github/manifests/web-deployment.yaml 
        kubectl apply -f .github/manifests/configmap.yaml 
        kubectl apply -f .github/manifests/web-service.yaml 
